### ISSUE TITLE
Secure Element communication always get error.

### ISSUE THREAD

**Issue by mingderwang** [will127534/HITCON-Badge-2018#1]
即使用 command line, 還是永遠無法成功寫入 Secure Element, 請問這是什麼問題
有 hardware reset Hotkeys 嗎? 我可以重置硬體.
否則這個冷錢包, 變成永遠不能用了?

**Comment by will127534** [comment]
Any log output?

**Comment by mingderwang** [comment]
Please input mnemonic at a time:
[console_input_mnemonic] Get:stick hedgehog brave joke slam again object mask lunch purity sausage sheriff
[ReinitWallet] stick hedgehog brave joke slam again object mask lunch purity sausage sheriff
[init Secure Element] GetModeState Success
[Re-init SE] Mode:2==>NORMAL
[Re-init SE] State:37
[Re-init SE] Normal Mode, SE logut
[Re-init SE] Clear Wallet(BackToInit)
InitBackInit
Mode:NOHOST
[Re-init SE] Bind Reg
Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 40 00 00 00 00 00 00 00 00 00 00 
=======================================================
Error code:40==>Wrong first flag
[BindRegInit] Wrong first flag, try again

=======================================================
BindRegFinish
	00 00 
=======================================================
=======================================================
Cred_buf
	00 36 36 39 35 34 34 1F 6F 33 86 B6 F7 46 F4 0D 
	04 6A E4 EF 8A 60 D1 
=======================================================
[Re-init SE] Bind Login
Error!3
[Re-init SE] BindLogin Failed! Stop the reinit procedure[Re-init SE] Bind Login
[BindLogin] Login Success
[BindLogin perso mode] Pin Set!
[Re-init SE] BindLogin Success![Re-init SE] Set Security Policy
[SetSecurityPolicy] SECPO[0]:0
[SetSecurityPolicy] SECPO[0]:100
[Re-init SE] SetSecurityPolicy Success!
[Re-init SE] Mode:2==>NORMAL
[Re-init SE] State:0
[Re-init SE] InitWalletFromMnemonic
[InitWalletFromMnemonic] mnemonic /wo  passphrase
[InitWalletFromMnemonic] Wait for 1 min

約一分鐘後, 

ADPU transfer error:16
hdw_init_wallet_words failed

[Re-init SE] hdw_query_wallet_info
Error!10
[Re-init SE] hdw_query_wallet_info Failed! Stop the reinit procedureError!10
[Re-init SE] hdw_query_wallet_info Failed! Stop the reinit procedure!!CTRL = E0==>
20900000000000000
ADPU transfer error:32
[Re-init SE] hdw_query_wallet_info Failed! Stop the reinit procedureSecure Element Error -> Forced enter Cmdline
**************************************************************************
* _______ __ __                         ______           __              *
*|   |   |__|  |_.----.-----.-----.    |   __ \.---.-.--|  |.-----.-----.*
*|       |  |   _|  __|  _  |     |    |   __ <|  _  |  _  ||  _  |  -__|*
*|___|___|__|____|____|_____|__|__|    |______/|___._|_____||___  |_____|*
*                                                           |_____|      *
*                     ______ ______ ____   ______                        *
*                    |__    |      |_   | |  __  |                       *
*                    |    __|  --  |_|  |_|  __  |                       *
*                    |______|______|______|______|                       *
*                                                                        *
**************************************************************************
Hitcon Badge 2018 Cmdline interface
Version:1.0.12
enter help to see the cmd list

HitconBadge2018 >>

**Comment by will127534** [comment]
看起來InitWalletFromMnemonic有成功，可是後面的斷掉(InitWalletFromMnemonic跑太久)
可以進到cmdline手動設定新的錢包看看
```
CreateAccount 60 0 ETH
CreateNextAddr 0
```

**Comment by mingderwang** [comment]
它會停在 “Waiting for connection ...." 的畫面? Reset 也沒用. 請問怎麼辦? 有沒有  Hard Reset Keys?

**Comment by will127534** [comment]
到這一步就成功了，就只要透過手機配對就可以連上
手冊在這邊: http://I.hitcon.org/2018-cmt-wallet

**Comment by will127534** [comment]
另外沒有所謂的Hard Reset,只有 Re initialize Wallet(A.K.A清除Secure Element的內容)
還有重新綁定手機(BLE Reparing)

**Comment by mingderwang** [comment]
@will127534  手冊連結不見了. 可以提供其他 link 嗎?

**Comment by will127534** [comment]
https://docs.google.com/document/u/2/d/e/2PACX-1vRb_zjz9M0kTQbKd5epGVAjOwNzlQjt-gbdVxHlRrMKPlPgDsRIGXLNuIBSWFnGFIEk-_6FnmWNerVz/pub

**Comment by mingderwang** [comment]
@will127534  Thanks

**Comment by mingderwang** [comment]
@will127534  Thanks, it back to normal.
