### ISSUE TITLE
 secure element 每次 initial wallet 都 fail, 之後交易iOS 手機上都出現 Error Invalid RLP.

### ISSUE THREAD

**Issue by mingderwang** [will127534/HITCON-Badge-2018#2]
請問是什麼原因, 有解嗎? 硬體 secure element IC 有壞掉嗎?

**Comment by will127534** [comment]
initial wallet 如果 Failed, 那交易的時候應該會失敗
因為Secure element並沒有初始化成功
可能還是要看一下Console的Log

**Comment by mingderwang** [comment]
但您教的方法, 可以都成功, 是不是硬體壞了？

HitconBadge2018 >> CreateAccount 60 0 ETH
Creating account: m/44'/3c000000/00000000
CreateAccount Success!!

HitconBadge2018 >> CreateNextAddr 0
=======================================================
Addr
        00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
        00 00 00 00 00 00 00 00 00 
=======================================================
CreateNextAddr Success!!

HitconBadge2018 >>

**Comment by mingderwang** [comment]
error logs:  
HitconBadge2018 >> [Main] BLE Connected
[BLE Process] New Balance Get!
D993B58AFC3DADDF5E96F62131D5AAAC7EFA8EC1407FEDAD5FFE9673C5D3CBF64CAEAEAA5166B5D3DF8A737722E9123BEE782248B4672DF2449BD8DBB968852AA487EDD92C886AA305D6F2A5D0D7BF23FD3049D7DFE0BD414A33E415F4AE6E000000000000000000000000000000000000000000000000
[BLE decript] encripted:128
7EFA8EC1407FEDAD5FFE9673C5D3CBF64CAEAEAA5166B5D3DF8A737722E9123BEE782248B4672DF2449BD8DBB968852AA487EDD92C886AA305D6F2A5D0D7BF23FD3049D7DFE0BD414A33E415F4AE6E000000000000000000000000000000000000000000000000
[BLE decript] dencripted:4
1145318ADCED3B52454FDAEA84FC4F577F1EA66A8C28D7A3703DAD7740114503BC139665E7E9F863BA1BCFE635A2E87AA5B28000000244010101010101010101010101010101010279B4D95626B8BC8ED42FFB3FD12CF44667DDCB5B4E81CF9E1C1F2A25829A4667DDCB5B4E81CF9E1C1F2A25829A
[BLE Process] Update Balance:
[BLE Process] Address: 5318adced3b52454fdaea84fc4f5770f1ea66a8c
[BLE Process] Value: D7A3703DAD7740
[BLE Process] Wallet Balance Get! 
[BLE Process] Update Balance:
[BLE Process] Address: 503b0c139665e7e9f863ba1bcf0e635a2e87aa5b
[BLE Process] Value: 0000002440
[BLE Process] Hitcon Balance Get! 
[BLE Process] Address header ERROR, Return
[Main] New Balance:2.98
[Main] New HITCON_Balance:10.00
[BLE Process] New Transaction Get!
76765895675BC39C19A50926ABB19A6EA93D328C1463591C4D83B737CBF193D46C64301592DBFA6E4481931FC543565433DE8E8EB0261EC5EE791DA6BFC300000000000000000000000000000000000000000000000000000000000000000000000000000000
[BLE decript] encripted:128
EA93D328C1463591C4D83B737CBF193D46C64301592DBFA6E4481931FC543565433DE8E8EB0261EC5EE791DA6BFC300000000000000000000000000000000000000000000000000000000000000000000000000000000
[BLE decript] dencripted:4
1145318ADCED3B52454FDAEA84FC4F577F1EA66A8C28DE0B6B3A7640032168425285060444452324E23B3A5827D15BF26637833D594667DDCB5B4E81CF9E1C1F2A25829A4667DDCB5B4E81CF9E1C1F2A25829A4667DDCB5B4E81CF9E1C1F2A25829A4667DDCB5B4E81CF9E1C1F2A25829A
Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 37 
=======================================================
Error code:37==>Wrong HDW account ID
=======================================================
pre_trx_s
	80 B8 00 00 68 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 FF E4 5D 
	DA 4B 04 F7 08 FD 0B 21 F9 29 AF 32 4F 1F 1E 04 
	66 0C B6 A0 E8 4A E8 B5 16 A1 DF 0A 0B A4 88 74 
	62 61 B5 F8 6D 58 43 F0 FD E4 1F 1E 3A 28 F9 54 
	A1 85 C5 6A 05 88 6E 9F A0 C6 B9 A7 F6 48 00 00 
	05 00 01 00 
=======================================================
Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 24 
=======================================================
Error code:24==>Internal module error
Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 05 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 
=======================================================
Error code:5==>Wrong trx signing state
[BLE Process] Txn Length:1
[Main] Balance:2.98
[Main] HITCON_Balance:10.00
[Main Menu] QR code data:0x5318adced3b52454fdaea84fc4f5770f1ea66a8c

**Comment by will127534** [comment]
initwallet那邊可能出了問題，因為看起來Address是有問題的
QueryWalletInfo看看Wallet的狀態
QueryAllAccount看看目前Wallet的Account狀態

**Comment by mingderwang** [comment]
簡單講 initwallet 最後等1 分鐘, 之後一定 fail. 可以 (hard) reset secure element 嗎? 用 command line 也一樣

HitconBadge2018 >> QueryWalletInfo
hdw status 0x22
=======================================================
hdw name:
	48 69 74 63 6F 6E 20 42 61 64 67 65 20 32 30 31 
	38 00 5B 49 6E 69 74 57 61 6C 6C 65 74 46 72 6F 
=======================================================
=======================================================
hdw account ptr:
	00 00 00 00 
=======================================================
query_wallet Success!!

HitconBadge2018 >> QueryAllAccount
Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 37 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 
=======================================================
Error code:37==>Wrong HDW account ID
Query End!
hdw_query_all_account_info Success!!

HitconBadge2018 >>

**Comment by will127534** [comment]
看起來是Wallet並沒有正確的initialize成功
試試看跑一下InitWallet
然後再跑一次 CreateAccount+CreateNextAddr

最後我想在強調一次沒有"Hard Reset"，只有在不同State切換而已

**Comment by mingderwang** [comment]
我這樣重複做了好幾次了. 但我一直用同一組 Mnemonic word list

**Comment by will127534** [comment]
試試看InitWallet [Mnemonic word list]

**Comment by will127534** [comment]
跑完接著跑CreateAccount+CreateNextAddr
Address應該不會是0

**Comment by mingderwang** [comment]
[console_input_mnemonic] Get:InitWallet xxxxxxxx
[ReinitWallet] InitWallet xxxxxxx
[init Secure Element] GetModeState Success
[Re-init SE] Mode:2==>NORMAL
[Re-init SE] State:37
[Re-init SE] Normal Mode, SE logut
[Re-init SE] Clear Wallet(BackToInit)
InitBackInit
Mode:NOHOST
[Re-init SE] Bind Reg
Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 40 00 00 00 00 00 00 00 00 00 00 
=======================================================
Error code:40==>Wrong first flag
[BindRegInit] Wrong first flag, try again

=======================================================
BindRegFinish
	00 00 
=======================================================
=======================================================
Cred_buf
	00 39 39 35 35 31 35 24 0C 3B 75 0C C3 68 3C 9D 
	A4 66 4B F3 05 98 0F 
=======================================================

在輸入 Pin code 之前, 已經有看到幾個 Errors 了.

**Comment by will127534** [comment]
Wrong first flag是正常的，這只是在Binding的時候在找正確的first flag
看到BindRegFinish 00 00 就是正常的狀況

**Comment by mingderwang** [comment]
輸入 confirm Pin code, 無法按到正確得數字, 哈哈我手流汗, 電阻不對了, 我再試試看. 謝謝

**Comment by mingderwang** [comment]
我按 6 校正就好一點.
但, 不幸的是
還是一樣

Re-init SE] Bind Login
[BindLogin] Login Success
[BindLogin perso mode] Pin Set!
[Re-init SE] BindLogin Success![Re-init SE] Set Security Policy
[SetSecurityPolicy] SECPO[0]:0
[SetSecurityPolicy] SECPO[0]:100
[Re-init SE] SetSecurityPolicy Success!
[Re-init SE] Mode:2==>NORMAL
[Re-init SE] State:0
[Re-init SE] InitWalletFromMnemonic
[InitWalletFromMnemonic] mnemonic /wo  passphrase
[InitWalletFromMnemonic] Wait for 1 min
ADPU transfer error:16
hdw_init_wallet_words failed

[Re-init SE] hdw_query_wallet_info
Error!10
[Re-init SE] hdw_query_wallet_info Failed! Stop the reinit procedureError!10
[Re-init SE] hdw_query_wallet_info Failed! Stop the reinit procedure!!CTRL = E0==>
20900000000000000
ADPU transfer error:32
[Re-init SE] hdw_query_wallet_info Failed! Stop the reinit procedureSecure Element Error -> Forced enter Cmdline
**************************************************************************
* _______ __ __                         ______           __              *
*|   |   |__|  |_.----.-----.-----.    |   __ \.---.-.--|  |.-----.-----.*
*|       |  |   _|  __|  _  |     |    |   __ <|  _  |  _  ||  _  |  -__|*
*|___|___|__|____|____|_____|__|__|    |______/|___._|_____||___  |_____|*
*                                                           |_____|      *
*                     ______ ______ ____   ______                        *
*                    |__    |      |_   | |  __  |                       *
*                    |    __|  --  |_|  |_|  __  |                       *
*                    |______|______|______|______|                       *
*                                                                        *
**************************************************************************
Hitcon Badge 2018 Cmdline interface
Version:1.0.12
enter help to see the cmd list

HitconBadge2018 >>

**Comment by will127534** [comment]
對，到這個時候透過Console下
InitWallet [Mnemonic word list]
這樣看看

**Comment by mingderwang** [comment]
HitconBadge2018 >> InitWallet xxxx xxxx xxxx
Mnemonic words:xxxx xxxx xxx
[InitWalletFromMnemonic] mnemonic /wo  passphrase
[InitWalletFromMnemonic] Wait for 1 min

Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 31 
=======================================================
Error code:31==>Wrong HD wallet status
hdw_init_wallet_words failed

還是 failed

**Comment by mingderwang** [comment]
屢試不爽

**Comment by will127534** [comment]
OK，那這樣代表mnemonic應該有成功(因為在送一次會Error)
跑CreateAccount+CreateNextAddr看看

**Comment by mingderwang** [comment]
OK

**Comment by mingderwang** [comment]
address 還是 000000

HitconBadge2018 >> CreateAccount 60 0 ETH
Creating account: m/44'/3c000000/00000000
CreateAccount Success!!

HitconBadge2018 >> CreateNextAddr 0
=======================================================
Addr
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 
=======================================================
CreateNextAddr Success!!

HitconBadge2018 >>

**Comment by mingderwang** [comment]
這可以讓我進入正常, 帳號畫面. 但在用 iOS 手機經由 Hardware Wallet 認證後, 總是 出現 Error Invalid RLP 
transfer 失敗. 
我再試試看. 轉帳是否可以成功.

**Comment by will127534** [comment]
不，如果帳號沒有生成的話，那轉帳也會失敗(因為抓不到帳號)
我跑一次看看

**Comment by mingderwang** [comment]
它有問題, 不管我initWallet 幾次, 他主畫面一直是舊帳號的 Ether 數量, 表示帳號一直沒變

**Comment by mingderwang** [comment]
這就是我ㄧ直想要有成功的方法 init wallet, 但都失敗. 也有用過 generate random key, 也沒用. 因為是寫不進去 secure element

**Comment by will127534** [comment]
現在在講的都是在Cmdline Interface當中操作
CreateAccount 60 0 ETH
和
CreateNextAddr 0
跑完之後
QueryAllAccount的結果是甚麼?

**Comment by will127534** [comment]
我還是整理一下流程
1.重新Init出問題之後=>在Cmdline底下打指令手動設定
2.先看QueryWalletInfo，如果Status = 0x00 => 手動打InitWallet [Wordlist]
如果Status = 0x22 => Wordlist 有成功寫入，到下一步
3.CreateAccount 60 0 ETH + CreateNextAddr 0
這時候QueryAllAccount應該會有資料出來
QueryWalletInfo的Account pointer也會是0x01

**Comment by mingderwang** [comment]
wait, 我重新弄. reset 後 Cmdline 會沒反應.

**Comment by will127534** [comment]
Cmdline沒反應的話應該是卡在BLE init?
因為看你的說明似乎是在Badge上面跑re init

**Comment by mingderwang** [comment]
HitconBadge2018 >> QueryWalletInfo
hdw status 0x22
=======================================================
hdw name:
	48 69 74 63 6F 6E 20 42 61 64 67 65 20 32 30 31 
	38 00 5B 49 6E 69 74 57 61 6C 6C 65 74 46 72 6F 
=======================================================
=======================================================
hdw account ptr:
	00 00 00 00 
=======================================================
query_wallet Success!!

**Comment by will127534** [comment]
CreateAccount 60 0 ETH <=這行似乎沒有成功
再跑一次看看

**Comment by mingderwang** [comment]
HitconBadge2018 >> CreateAccount 60 0 ETH
Creating account: m/44'/3c000000/00000000
CreateAccount Success!!

**Comment by will127534** [comment]
跑第二次看看

**Comment by mingderwang** [comment]
QueryAllAccount 沒有 Account ID?

且 CreateNextAddr 0 沒有 address?

HitconBadge2018 >> CreateNextAddr 0
=======================================================
Addr
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 
=======================================================
CreateNextAddr Success!!



HitconBadge2018 >> QueryAllAccount
=======================================================
ACCOUNT ID
	00 00 00 00 
=======================================================
=======================================================
ACCOUNT PURPOSE
	2C 00 00 80 
=======================================================
=======================================================
ACCOUNT COINTYPE
	3C 00 00 00 
=======================================================
=======================================================
ACCOUNT BALANCE
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
=======================================================

Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 37 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 
=======================================================
Error code:37==>Wrong HDW account ID
Query End!
hdw_query_all_account_info Success!!

HitconBadge2018 >>

**Comment by mingderwang** [comment]
Account pointer 是 1

QueryWalletInfo
hdw status 0x22
=======================================================
hdw name:
	48 69 74 63 6F 6E 20 42 61 64 67 65 20 32 30 31 
	38 00 5B 49 6E 69 74 57 61 6C 6C 65 74 46 72 6F 
=======================================================
=======================================================
hdw account ptr:
	01 00 00 00 
=======================================================
query_wallet Success!!

HitconBadge2018 >>

**Comment by will127534** [comment]
QueryAllAccount <=查詢Wallet所有的Account
這樣看起來Create Account正常了
CreateNextAddr 0再跑一次

**Comment by mingderwang** [comment]
但畫面還是 Secure Element communication error 喔！

**Comment by will127534** [comment]
Cmdline不會改變畫面

**Comment by mingderwang** [comment]
QueryAllAccount
=======================================================
ACCOUNT ID
	00 00 00 00 
=======================================================
=======================================================
ACCOUNT PURPOSE
	2C 00 00 80 
=======================================================
=======================================================
ACCOUNT COINTYPE
	3C 00 00 00 
=======================================================
=======================================================
ACCOUNT BALANCE
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
=======================================================

Error at 90 00

=======================================================
ADPU rx buf
	02 00 66 37 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 
=======================================================
Error code:37==>Wrong HDW account ID
Query End!
hdw_query_all_account_info Success!!

HitconBadge2018 >>

**Comment by will127534** [comment]
打一下這個指令:CreateNextAddr 0

**Comment by mingderwang** [comment]
CreateNextAddr 0
=======================================================
Addr
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
	00 00 00 00 00 00 00 00 00 
=======================================================
CreateNextAddr Success!!

HitconBadge2018 >>

**Comment by will127534** [comment]
好，接下來 QueryAccountKey 0 0

**Comment by mingderwang** [comment]
有東西了

HitconBadge2018 >> QueryAccountKey 0 0
Query account id: 0 Key_id:0
=======================================================
pub key
	DC 3A 95 4E 7C 37 2F CA A0 B9 27 F3 85 62 59 F3 
	70 4E 9D 3F CB 63 1C 89 A4 CA 65 12 EE 23 64 5A 
	9F E7 69 71 20 27 7D 80 A9 3F 4C B4 44 80 A3 F5 
	B2 14 77 4B 11 FB C8 BE 4F B2 C4 4B 7B 28 59 33 
=======================================================
ETH Address:96f90e974fa367e7d9167b24bd72078f7c6884f0
QueryAccountKey Success!!

**Comment by will127534** [comment]
OK,按下Reset，這時候應該就正常了

**Comment by mingderwang** [comment]
我帳號裡有  2.9800 ETH 不正常吧? 還是沒變

**Comment by will127534** [comment]
手機要連上後才能Update
所以可能要重新配對BLE?

**Comment by mingderwang** [comment]
這是我 reset 的 console 畫面, 很像同一個 pub key

HitconBadge2018 >> [Setup] Program Start
[Setup] Hardware setup done
[Setup] Display setup done
=======================================================
Version
	D0 A5 E3 B0 43 57 30 31 36 33 18 07 20 17 55 29 
=======================================================
[init Secure Element] GetVersion Success
=======================================================
Secure Element Version
	D0 A5 E3 B0 43 57 30 31 36 33 18 07 20 17 55 29 
=======================================================
[init Secure Element] GetModeState Success
[init Secure Element] Mode:2
[init Secure Element] State:0
[init Secure Element] NORMAL mode
[init Secure Element] Query Account Public Key
=======================================================
pub key
	DC 3A 95 4E 7C 37 2F CA A0 B9 27 F3 85 62 59 F3 
	70 4E 9D 3F CB 63 1C 89 A4 CA 65 12 EE 23 64 5A 
	9F E7 69 71 20 27 7D 80 A9 3F 4C B4 44 80 A3 F5 
	B2 14 77 4B 11 FB C8 BE 4F B2 C4 4B 7B 28 59 33 
=======================================================
[init Secure Element] hdw_query_account_key_info Success
[init Secure Element] Wallet Address:96f90e974fa367e7d9167b24bd72078f7c6884f0
[quary_erc20s] ERC20 Found
[quary_erc20s] New ERC20 Get:HTN
[quary_erc20s] ERC20:0
	Contract Address:503b0c139665e7e9f863ba1bcf0e635a2e87aa5b
	Name:HTN
[Setup] Security Element setup done
[BLE init] BLE Changed:0
[init_BLE] LFLASH_Saved_UUID:
	ServiceUUID:	18548cfe-459e-0b32-d995-4a66ac5395a0
	Transaction_UUID:	1bf29889-459e-0b32-d995-4a66ac5395a0
	Txn_UUID:	07469c0a-459e-0b32-d995-4a66ac5395a0
	AddERC20_UUID:	34b74b26-459e-0b32-d995-4a66ac5395a0
	Balance_UUID:	db0d75cb-459e-0b32-d995-4a66ac5395a0
	General_CMD_UUID:	e04c034c-459e-0b32-d995-4a66ac5395a0
	General_Data_UUID:	bfa5f6e9-459e-0b32-d995-4a66ac5395a0
[BLE init] LFLASH_Saved_AESKey: 9C 9E DB 43 F4 98 B7 D0 25 48 9B CE 36 36 18 55 
[BLE init] Device Address = [93:32:27:F9:65:9C(RAN)]
[Setup] BLE setup done
[Main] Balance:2.98
[Main] HITCON_Balance:10.00
[Main Menu] QR code data:0x96f90e974fa367e7d9167b24bd72078f7c6884f0
[Setup] Main menu done
**************************************************************************
* _______ __ __                         ______           __              *
*|   |   |__|  |_.----.-----.-----.    |   __ \.---.-.--|  |.-----.-----.*
*|       |  |   _|  __|  _  |     |    |   __ <|  _  |  _  ||  _  |  -__|*
*|___|___|__|____|____|_____|__|__|    |______/|___._|_____||___  |_____|*
*                                                           |_____|      *
*                     ______ ______ ____   ______                        *
*                    |__    |      |_   | |  __  |                       *
*                    |    __|  --  |_|  |_|  __  |                       *
*                    |______|______|______|______|                       *
*                                                                        *
**************************************************************************
Hitcon Badge 2018 Cmdline interface
Version:1.0.12
enter help to see the cmd list

HitconBadge2018 >>

**Comment by will127534** [comment]
手機有跟Badge重新配對過了嗎?
要透過手機Badge才能Update Balance

**Comment by mingderwang** [comment]
OK. 我試試手機, 成功了. 你救了我的 Hardware wallet. 要連線後 帳號資料才會更新. 現在是 0.000 ETH 0 Hitcon.

Thanks you.

**Comment by will127534** [comment]
只能說Secure Element 溝通出問題的時候，Recovery機制並沒有做得很好
我大概最近會Update看看能不能比較穩定

**Comment by mingderwang** [comment]
firmware 更新跟 source code compiled 步驟, 是否可以寫在 wiki. 大家可以一起 maintain.

**Comment by will127534** [comment]
Sure,我下周補一下Wiki

**Comment by mingderwang** [comment]
我有用過 arduino 開發工具, 但不知要怎麼 使用 Badge_Linkit7697_V1.02.tar.bz2 與
package_hitcon_badge_index.json 這兩個檔案. 有網站可學嗎

**Comment by mingderwang** [comment]
Thanks.

**Comment by will127534** [comment]
有，請參考https://docs.labs.mediatek.com/resource/linkit7697-arduino/en/environment-setup
把網址換成:https://raw.githubusercontent.com/will127534/HITCON-Badge-2018/master/Software/Arduino_packages/package_hitcon_badge_index.json
即可
